version: '2'
services:
 mongo:
  image: mongo
  volumes:
   - /data/mongodb/db:/data/db
  ports:
   - "27017:27017"


 api:
  build: .
  command: node ./bin/www
  volumes:
   - api-img:/public/plantillas/
  ports:
   - "80:80"
  links:
   - mongo

volumes:
  api-img:
    driver: local
