version: '2'
services:
 mongo:
  container_name: mongo
  image: mongo:3.6.0
  volumes:
   - /data/db:/data/db
  ports:
   - "27017:27017"
   
api:
    container_name: cscfutsal
    restart: always
    build: .
    command: node ./bin/www
    volumes:
     - api-img:/CSCFUTSAL/public/plantillas
    ports:
     - "80:80"
    links:
     - mongo
     
volumes:
  api-img:
    driver: local
